#!/bin/bash
# Add configuration values for a given device serial

if [ -z "${DEVICE_LOOKUP_SERVER}" ];
then
  server_url=http://127.0.0.1
else
  server_url=${DEVICE_LOOKUP_SERVER}
fi

if [ -z "${DEVICE_LOOKUP_PORT}" ];
then
  port="$(snapctl get port 2>/dev/null)"
  # Validate it
  if ! expr "$port" : '^[0-9]*$' > /dev/null; then
    port=8080
  fi
else
  port=${DEVICE_LOOKUP_PORT}
fi

usage ()
{
  echo "usage: $0 SERIAL FILE_PATH"
  exit 1
}

if [ $# -ne 2 ];
then
  usage
fi

serial=$1
file_path=$2

file_contents=$(cat $file_path)
echo $file_contents | jq -re 2>&1>/dev/null

if [ $? -ne 0 ];
then
  echo "Invalid JSON input"
  exit 1
fi

json=$(jq -n \
    --arg serial "$serial" \
    --argjson file_contents "$file_contents" \
    '{($serial): $file_contents}')
OUT=$(curl -s -X POST -H "Content-Type: application/json" -d "$json" $server_url:$port/devices)
echo $OUT | jq
