#!/bin/bash
# Add configuration values for a given device serial

usage ()
{
  echo "usage: $0 SERIAL FILE_PATH"
  exit 1
}

if [ $# -ne 2 ];
then
  usage
fi

serial=$1
file_path=$2

file_contents=$(cat $file_path | jq --raw-input --slurp)
echo $file_contents | yq -re 2>1&>/dev/null

if [ $? -ne 0 ];
then
  echo "Invalid YaML input"
  exit 1
fi

port="$(snapctl get port 2>/dev/null)"
# Validate it
if ! expr "$port" : '^[0-9]*$' > /dev/null; then
    port=8080
fi

json=$(jq -n \
    --arg serial "$serial" \
    --argjson file_contents "$file_contents" \
    '{($serial): $file_contents}')
OUT=$(curl -s -X POST -H "Content-Type: application/json" -d "$json" http://127.0.0.1:$port/add-autoinstall)
echo $OUT
