#!/bin/bash
# Query service by serial number for configuration values

usage ()
{
  echo "usage: $0 SERIAL"
  exit 1
}

if [ $# -gt 0 ];
then
  if [ $1 == "-h" ];
  then
    usage
    exit
  fi
  serial=$1
fi

port="$(snapctl get port 2>/dev/null)"
# Validate it
if ! expr "$port" : '^[0-9]*$' > /dev/null; then
  port=8080
fi

OUT=$(curl -s -X GET http://127.0.0.1:$port/autoinstall?serial=$serial)
echo $OUT | yq
