#!/bin/bash
# Query service by serial number for configuration values

usage ()
{
  echo "usage: $0 SERIAL"
  exit 1
}

if [ $# -ne 1 ];
then
  usage
fi

port="$(snapctl get port 2>/dev/null)"
# Validate it
if ! expr "$port" : '^[0-9]*$' > /dev/null; then
    port=5000
fi

serial=$1
json=$(jq -n \
  --arg serial "$serial" \
  '{serial: $serial}')
OUT=$(curl -s -X POST -H "Content-Type: application/json" -d "$json" http://127.0.0.1:$port/query)
echo $OUT
