#!/bin/bash
# Query service by serial number for configuration values

usage ()
{
  echo "usage: $0 SERIAL"
  exit 1
}

if [ $# -gt 0 ];
then
  if [ $1 == "-h" ];
  then
    usage
    exit
  fi
  serial=$1
fi

port="$(snapctl get port 2>/dev/null)"
# Validate it
if ! expr "$port" : '^[0-9]*$' > /dev/null; then
  port=8080
fi

if [ $serial ];
then
  json=$(jq -n \
    --arg serial "$serial" \
    '{serial: $serial}')
  OUT=$(curl -s -X POST -H "Content-Type: application/json" -d "$json" http://127.0.0.1:$port/query)
else
  OUT=$(curl -s -X GET -H "Content-Type: application/json" http://127.0.0.1:$port/)
fi

echo $OUT | jq
